/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication_final;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hishan Kavishka
 */
public class Create_Account extends javax.swing.JFrame {

    /**
     * Creates new form Create_Account
     */
    public Create_Account() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Create_Account.RoundedPanel(80, Color.white);
        txt_Firstname = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_password_reenterd = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btn_signup = new Create_Account.RoundedPanel(20, Color.blue);
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txt_dob = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txt_phone = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txt_address = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btn_close = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        left_panel = new Create_Account.RoundedPanel(80, Color.blue);
        head = new javax.swing.JLabel();
        hed_sep = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbl_wrn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1123, 643));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1123, 643));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 610));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Firstname.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_Firstname.setForeground(new java.awt.Color(102, 102, 102));
        txt_Firstname.setToolTipText("");
        txt_Firstname.setBorder(null);
        txt_Firstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_FirstnameMouseClicked(evt);
            }
        });
        jPanel1.add(txt_Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 390, 20));

        txt_password.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_password.setForeground(new java.awt.Color(102, 102, 102));
        txt_password.setToolTipText("");
        txt_password.setBorder(null);
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 170, 20));

        txt_password_reenterd.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_password_reenterd.setForeground(new java.awt.Color(102, 102, 102));
        txt_password_reenterd.setBorder(null);
        txt_password_reenterd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_password_reenterdMouseClicked(evt);
            }
        });
        txt_password_reenterd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_password_reenterdKeyReleased(evt);
            }
        });
        jPanel1.add(txt_password_reenterd, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 170, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 170, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 390, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 170, 10));

        btn_signup.setBackground(new java.awt.Color(41, 53, 65));
        btn_signup.setOpaque(false);
        btn_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_signupMousePressed(evt);
            }
        });
        btn_signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sign Up");
        btn_signup.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 12, -1, -1));

        jPanel1.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 390, 60));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 150, 50));

        txt_surname.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_surname.setForeground(new java.awt.Color(102, 102, 102));
        txt_surname.setToolTipText("");
        txt_surname.setBorder(null);
        jPanel1.add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 390, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 390, 10));

        txt_email.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_email.setForeground(new java.awt.Color(102, 102, 102));
        txt_email.setToolTipText("");
        txt_email.setBorder(null);
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emailMouseClicked(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 170, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 170, 10));

        txt_dob.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(102, 102, 102));
        txt_dob.setToolTipText("");
        txt_dob.setBorder(null);
        txt_dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_dobMouseClicked(evt);
            }
        });
        jPanel1.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 170, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 170, 10));

        txt_phone.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(102, 102, 102));
        txt_phone.setToolTipText("");
        txt_phone.setBorder(null);
        txt_phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_phoneMouseClicked(evt);
            }
        });
        jPanel1.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 390, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 390, 10));

        txt_address.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        txt_address.setForeground(new java.awt.Color(102, 102, 102));
        txt_address.setToolTipText("");
        txt_address.setBorder(null);
        txt_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_addressMouseClicked(evt);
            }
        });
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 390, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 390, 10));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/icons8-close-window-48.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        jPanel1.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Surname");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 150, 50));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("First Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 150, 50));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 150, 50));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Re-Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 150, 50));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Email");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 150, 50));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Date of Birth");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 150, 50));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Phone Number");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 150, 50));

        left_panel.setBackground(new java.awt.Color(255, 51, 204));
        left_panel.setOpaque(false);
        left_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setFont(new java.awt.Font("Calibri", 1, 38)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("Sign Up");
        left_panel.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 40));

        hed_sep.setForeground(new java.awt.Color(255, 255, 255));
        hed_sep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        left_panel.add(hed_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 50, 7));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/triangles.png"))); // NOI18N
        left_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 580, -1));

        jPanel1.add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 610));

        lbl_wrn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_wrn.setForeground(new java.awt.Color(102, 102, 102));
        lbl_wrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_wrnMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_wrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1110, 609));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_password_reenterdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_password_reenterdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password_reenterdKeyReleased

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_passwordKeyReleased

    private void btn_signupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signupMousePressed
        // TODO add your handling code here:
        String surname = txt_surname.getText();
        String fname = txt_Firstname.getText();
        String passwd = txt_password.getText();
        String repasswd = txt_password_reenterd.getText();
        String email = txt_email.getText();
        String phone = txt_phone.getText();
        String Date = txt_dob.getText();
        String Address = txt_address.getText();

        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {
            if (passwd.equals(repasswd)) {

                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                Date date = fmt.parse(Date);
                java.util.Date utilDate = date;
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                final String stringDate = dateFormat.format(utilDate);
                final java.sql.Date sqlDate = java.sql.Date.valueOf(stringDate);

                con = a.connect();
                String sql = "INSERT INTO `login`(`firstname`,`password`, `user_status`, `Email`,`phone`,`address`,`surname`,`dob` ) VALUES (?,?,?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);

                pst.setString(1, fname);
                pst.setString(2, passwd);
                pst.setString(3, "user");
                pst.setString(4, email);
                pst.setString(5, phone);
                pst.setString(6, Address);
                pst.setString(7, surname);
                pst.setDate(8, sqlDate);

                pst.executeUpdate();
                pst.close();
                con.close();
                lbl_wrn.setText("Account Created");
                lbl_wrn.setForeground(Color.red);

            } else {
                
                lbl_wrn.setText("Password Mismatch");
                lbl_wrn.setForeground(Color.red);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_signupMousePressed

    private void txt_FirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FirstnameMouseClicked
        // TODO add your handling code here:
        txt_Firstname.setText("");
    }//GEN-LAST:event_txt_FirstnameMouseClicked

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        // TODO add your handling code here:
        txt_password.setText("");
    }//GEN-LAST:event_txt_passwordMouseClicked

    private void txt_password_reenterdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_password_reenterdMouseClicked
        // TODO add your handling code here:
        txt_password_reenterd.setText("");
    }//GEN-LAST:event_txt_password_reenterdMouseClicked

    private void txt_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMouseClicked
        // TODO add your handling code here:
        txt_email.setText("");
    }//GEN-LAST:event_txt_emailMouseClicked

    private void txt_dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dobMouseClicked
        // TODO add your handling code here:
        txt_dob.setText("");
    }//GEN-LAST:event_txt_dobMouseClicked

    private void txt_phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phoneMouseClicked
        // TODO add your handling code here:
        txt_phone.setText("");
    }//GEN-LAST:event_txt_phoneMouseClicked

    private void txt_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addressMouseClicked
        // TODO add your handling code here:
        txt_address.setText("");
    }//GEN-LAST:event_txt_addressMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void lbl_wrnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_wrnMouseClicked

        Create_Account acc = new Create_Account();
        acc.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_lbl_wrnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_close;
    private javax.swing.JPanel btn_signup;
    private javax.swing.JLabel head;
    private javax.swing.JSeparator hed_sep;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_wrn;
    private javax.swing.JPanel left_panel;
    private javax.swing.JTextField txt_Firstname;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_password_reenterd;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//            
        }
    }

}
