/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication_final;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hishan Kavishka
 */
public class Report extends javax.swing.JFrame {

    String s;

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        //Update Table
        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {
            con = a.connect();
            String sql = "Select * from timetable";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            jTable_report.setModel(DbUtils.resultSetToTableModel(rs));

            Statement st = con.createStatement();
            String sqlq1 = "SELECT * FROM login WHERE `sno`='" + current + "'";
            ResultSet rst = st.executeQuery(sqlq1);
            if (rst.next()) {
                byte[] img = rst.getBytes("Image");
                if (img == null) {
                    String status = rst.getString("firstname");
                    lbl_Realtime_username.setText("..Hello " + status + "..");

                    txt_surnanme.setText(rst.getString("surname"));
                    txt_firstname.setText(status);
                    txt_passwd.setText(rst.getString("password"));
                    txt_email.setText(rst.getString("Email"));
                    txt_dob.setText(rst.getString("dob"));
                    txt_mobile.setText(rst.getString("phone"));
                    txt_address.setText(rst.getString("address"));

                    basepanel_settings.setVisible(false);
                    basepanel_Account.setVisible(false);
                    basepanel_reser.setVisible(false);
                    basepanel_home.setVisible(true);
                } else {
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lbl_image.setIcon(newImage);

                    String status = rst.getString("firstname");
                    lbl_Realtime_username.setText("..Hello " + status + "..");

                    txt_surnanme.setText(rst.getString("surname"));
                    txt_firstname.setText(status);
                    txt_passwd.setText(rst.getString("password"));
                    txt_email.setText(rst.getString("Email"));
                    txt_dob.setText(rst.getString("dob"));
                    txt_mobile.setText(rst.getString("phone"));
                    txt_address.setText(rst.getString("address"));

                    basepanel_settings.setVisible(false);
                    basepanel_Account.setVisible(false);
                    basepanel_reser.setVisible(false);
                    basepanel_home.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Invalid User");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left_main_panel = new javax.swing.JPanel();
        btn_Acc = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        btn_reser = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btn_settings = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        panel_Repo = new javax.swing.JPanel();
        panel_Acc = new javax.swing.JPanel();
        panel_settings = new javax.swing.JPanel();
        btn_logout = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        panel_logout = new javax.swing.JPanel();
        panel_top = new javax.swing.JPanel();
        close_button = new javax.swing.JLabel();
        basepanel_home = new javax.swing.JPanel();
        lbl_username4 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_username3 = new javax.swing.JLabel();
        txt_from = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_username2 = new javax.swing.JLabel();
        txt_to = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_Search = new Report.RoundedPanel(20, Color.blue);
        txt_search = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_report = new javax.swing.JTable();
        btn_Book = new Report.RoundedPanel(20, Color.blue);
        txt_Book = new javax.swing.JLabel();
        basepanel_Account = new javax.swing.JPanel();
        txt_surnanme = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txt_passwd = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        txt_dob = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        txt_mobile = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        txt_firstname = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        txt_address = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        lbl_image = new javax.swing.JLabel();
        btn_image = new Report.RoundedPanel(20, Color.blue);
        jLabel6 = new javax.swing.JLabel();
        lbl_Realtime_username = new javax.swing.JLabel();
        btn_acc_update = new Report.RoundedPanel(50, Color.blue);
        jLabel13 = new javax.swing.JLabel();
        basepanel_settings = new javax.swing.JPanel();
        txt_arrival = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_depature = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txt_condition = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txt_seat = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        txt_avi_seat = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txt_From = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        txt_To = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        txt_Date = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btn_Delete = new Report.RoundedPanel(50, Color.blue);
        jLabel11 = new javax.swing.JLabel();
        btn_Update = new Report.RoundedPanel(50, Color.blue);
        jLabel8 = new javax.swing.JLabel();
        btn_Create = new Report.RoundedPanel(50, Color.blue);
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        txt_bus_no = new javax.swing.JTextField();
        txt_delete_bus_no = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        basepanel_reser = new javax.swing.JPanel();
        Rese_Scroll_pane = new javax.swing.JScrollPane();
        Rese_table = new javax.swing.JTable();
        btn_reser_cancel = new Report.RoundedPanel(20, Color.blue);
        txt_Book1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_main_panel.setBackground(new java.awt.Color(41, 39, 40));
        left_main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Acc.setBackground(new java.awt.Color(41, 39, 40));
        btn_Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AccMousePressed(evt);
            }
        });
        btn_Acc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Account");
        btn_Acc.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/icons8-user-account-skin-type-7-48.png"))); // NOI18N
        btn_Acc.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 50, 60));

        left_main_panel.add(btn_Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 207, 60));

        btn_home.setBackground(new java.awt.Color(41, 53, 65));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Home");
        btn_home.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/Home_48px.png"))); // NOI18N
        btn_home.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 50, 60));

        left_main_panel.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 207, 60));

        btn_reser.setBackground(new java.awt.Color(41, 39, 40));
        btn_reser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_reserMousePressed(evt);
            }
        });
        btn_reser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Reservations");
        btn_reser.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/icons8-doughnut-chart-48.png"))); // NOI18N
        btn_reser.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, 64));

        left_main_panel.add(btn_reser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 207, 60));

        btn_settings.setBackground(new java.awt.Color(41, 39, 40));
        btn_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_settingsMousePressed(evt);
            }
        });
        btn_settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Settings");
        btn_settings.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/settings_48px.png"))); // NOI18N
        btn_settings.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 50, 64));

        left_main_panel.add(btn_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 207, 60));

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        left_main_panel.add(panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 60));

        panel_Repo.setBackground(new java.awt.Color(41, 39, 40));

        javax.swing.GroupLayout panel_RepoLayout = new javax.swing.GroupLayout(panel_Repo);
        panel_Repo.setLayout(panel_RepoLayout);
        panel_RepoLayout.setHorizontalGroup(
            panel_RepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panel_RepoLayout.setVerticalGroup(
            panel_RepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        left_main_panel.add(panel_Repo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 60));

        panel_Acc.setBackground(new java.awt.Color(41, 39, 40));

        javax.swing.GroupLayout panel_AccLayout = new javax.swing.GroupLayout(panel_Acc);
        panel_Acc.setLayout(panel_AccLayout);
        panel_AccLayout.setHorizontalGroup(
            panel_AccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panel_AccLayout.setVerticalGroup(
            panel_AccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        left_main_panel.add(panel_Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 60));

        panel_settings.setBackground(new java.awt.Color(41, 39, 40));

        javax.swing.GroupLayout panel_settingsLayout = new javax.swing.GroupLayout(panel_settings);
        panel_settings.setLayout(panel_settingsLayout);
        panel_settingsLayout.setHorizontalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panel_settingsLayout.setVerticalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        left_main_panel.add(panel_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 60));

        btn_logout.setBackground(new java.awt.Color(51, 51, 51));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_logoutMousePressed(evt);
            }
        });
        btn_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Logout");
        btn_logout.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/icons8-exit-48.png"))); // NOI18N
        btn_logout.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 50, 64));

        left_main_panel.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 756, 207, -1));

        panel_logout.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout panel_logoutLayout = new javax.swing.GroupLayout(panel_logout);
        panel_logout.setLayout(panel_logoutLayout);
        panel_logoutLayout.setHorizontalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panel_logoutLayout.setVerticalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        left_main_panel.add(panel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 755, -1, 60));

        jPanel1.add(left_main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 820));

        panel_top.setBackground(new java.awt.Color(102, 102, 255));
        panel_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/icons8-close-window-48.png"))); // NOI18N
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                close_buttonMousePressed(evt);
            }
        });
        panel_top.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jPanel1.add(panel_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1312, 80));

        basepanel_home.setBackground(new java.awt.Color(255, 255, 255));
        basepanel_home.setForeground(new java.awt.Color(255, 255, 255));
        basepanel_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username4.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        lbl_username4.setForeground(new java.awt.Color(153, 153, 153));
        lbl_username4.setText("Date");
        basepanel_home.add(lbl_username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 70, 40));

        txt_date.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_date.setForeground(new java.awt.Color(153, 153, 153));
        txt_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_date.setText("YYYY/MM/DD");
        txt_date.setBorder(null);
        txt_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_dateMouseClicked(evt);
            }
        });
        basepanel_home.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, 20));
        basepanel_home.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 180, 10));

        lbl_username3.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        lbl_username3.setForeground(new java.awt.Color(153, 153, 153));
        lbl_username3.setText("From");
        basepanel_home.add(lbl_username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 60, 40));

        txt_from.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_from.setForeground(new java.awt.Color(153, 153, 153));
        txt_from.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_from.setText("From");
        txt_from.setBorder(null);
        txt_from.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_fromMouseClicked(evt);
            }
        });
        basepanel_home.add(txt_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 180, 20));
        basepanel_home.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 180, 10));

        lbl_username2.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        lbl_username2.setForeground(new java.awt.Color(153, 153, 153));
        lbl_username2.setText("To");
        basepanel_home.add(lbl_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 40, 40));

        txt_to.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_to.setForeground(new java.awt.Color(153, 153, 153));
        txt_to.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_to.setText("To");
        txt_to.setBorder(null);
        txt_to.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_toMouseClicked(evt);
            }
        });
        basepanel_home.add(txt_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 180, 20));
        basepanel_home.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 180, 10));

        btn_Search.setBackground(new java.awt.Color(41, 53, 65));
        btn_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_Search.setOpaque(false);
        btn_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_SearchMousePressed(evt);
            }
        });
        btn_Search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        txt_search.setForeground(new java.awt.Color(255, 255, 255));
        txt_search.setText("Search");
        btn_Search.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        basepanel_home.add(btn_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 280, 40));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable_report.setAutoCreateRowSorter(true);
        jTable_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_report.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_report.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable_report.setRowHeight(25);
        jTable_report.setSelectionBackground(new java.awt.Color(41, 39, 40));
        jScrollPane2.setViewportView(jTable_report);

        basepanel_home.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1220, 530));

        btn_Book.setBackground(new java.awt.Color(41, 53, 65));
        btn_Book.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_Book.setOpaque(false);
        btn_Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_BookMousePressed(evt);
            }
        });
        btn_Book.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Book.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        txt_Book.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book.setText("Book");
        btn_Book.add(txt_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 20));

        basepanel_home.add(btn_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 280, 40));

        jPanel1.add(basepanel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 1310, 740));

        basepanel_Account.setBackground(new java.awt.Color(255, 255, 255));
        basepanel_Account.setForeground(new java.awt.Color(255, 255, 255));
        basepanel_Account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_surnanme.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_surnanme.setForeground(new java.awt.Color(153, 153, 153));
        txt_surnanme.setText("Surename");
        txt_surnanme.setBorder(null);
        txt_surnanme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_surnanmeMouseClicked(evt);
            }
        });
        basepanel_Account.add(txt_surnanme, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 390, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 38)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("User Profile");
        basepanel_Account.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 300, 50));

        jSeparator18.setForeground(new java.awt.Color(0, 255, 255));
        jSeparator18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 5, true));
        basepanel_Account.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, 5));
        basepanel_Account.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 390, 20));

        txt_passwd.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_passwd.setForeground(new java.awt.Color(153, 153, 153));
        txt_passwd.setText("Password");
        txt_passwd.setBorder(null);
        txt_passwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwdMouseClicked(evt);
            }
        });
        basepanel_Account.add(txt_passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 390, 40));
        basepanel_Account.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 390, 20));

        txt_dob.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(153, 153, 153));
        txt_dob.setText("Date of Birth");
        txt_dob.setBorder(null);
        txt_dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_dobMouseClicked(evt);
            }
        });
        basepanel_Account.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 390, 40));
        basepanel_Account.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 390, 20));

        txt_mobile.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_mobile.setForeground(new java.awt.Color(153, 153, 153));
        txt_mobile.setText("Phone Number");
        txt_mobile.setBorder(null);
        txt_mobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_mobileMouseClicked(evt);
            }
        });
        basepanel_Account.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 390, 40));
        basepanel_Account.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 390, 20));

        txt_email.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_email.setForeground(new java.awt.Color(153, 153, 153));
        txt_email.setText("Email ( username )");
        txt_email.setBorder(null);
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emailMouseClicked(evt);
            }
        });
        basepanel_Account.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 390, 40));
        basepanel_Account.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 390, 20));

        txt_firstname.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_firstname.setForeground(new java.awt.Color(153, 153, 153));
        txt_firstname.setText("First Name");
        txt_firstname.setToolTipText("");
        txt_firstname.setBorder(null);
        txt_firstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_firstnameMouseClicked(evt);
            }
        });
        basepanel_Account.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 390, 40));
        basepanel_Account.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 390, 20));

        txt_address.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_address.setForeground(new java.awt.Color(153, 153, 153));
        txt_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_address.setText("Address");
        txt_address.setBorder(null);
        txt_address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_addressMouseClicked(evt);
            }
        });
        basepanel_Account.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 870, 40));
        basepanel_Account.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 870, 20));

        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/user01.png"))); // NOI18N
        lbl_image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        basepanel_Account.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 250, 220));

        btn_image.setBackground(new java.awt.Color(41, 53, 65));
        btn_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_image.setOpaque(false);
        btn_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_imageMousePressed(evt);
            }
        });
        btn_image.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update Profile Picture");
        btn_image.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        basepanel_Account.add(btn_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 250, 40));

        lbl_Realtime_username.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_Realtime_username.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Realtime_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Realtime_username.setText("..Hello");
        basepanel_Account.add(lbl_Realtime_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 370, 70));

        btn_acc_update.setBackground(new java.awt.Color(41, 53, 65));
        btn_acc_update.setOpaque(false);
        btn_acc_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_acc_updateMousePressed(evt);
            }
        });
        btn_acc_update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Update");
        btn_acc_update.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, -1, 30));

        basepanel_Account.add(btn_acc_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 380, 60));

        jPanel1.add(basepanel_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 1310, 740));

        basepanel_settings.setBackground(new java.awt.Color(255, 255, 255));
        basepanel_settings.setForeground(new java.awt.Color(255, 255, 255));
        basepanel_settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_arrival.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_arrival.setForeground(new java.awt.Color(153, 153, 153));
        txt_arrival.setText("Arrival Time");
        txt_arrival.setBorder(null);
        txt_arrival.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_arrivalMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 390, 40));
        basepanel_settings.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 390, 20));

        txt_depature.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_depature.setForeground(new java.awt.Color(153, 153, 153));
        txt_depature.setText("Depature Time");
        txt_depature.setToolTipText("");
        txt_depature.setBorder(null);
        txt_depature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_depatureMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_depature, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 390, 40));
        basepanel_settings.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 390, 20));

        txt_condition.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_condition.setForeground(new java.awt.Color(153, 153, 153));
        txt_condition.setText("Bus Condition");
        txt_condition.setBorder(null);
        txt_condition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_conditionMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_condition, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 390, 40));
        basepanel_settings.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 390, 20));

        txt_seat.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_seat.setForeground(new java.awt.Color(153, 153, 153));
        txt_seat.setText("Seat Count");
        txt_seat.setBorder(null);
        txt_seat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_seatMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 390, 40));
        basepanel_settings.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 390, 20));

        txt_avi_seat.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_avi_seat.setForeground(new java.awt.Color(153, 153, 153));
        txt_avi_seat.setText("Avalible Seat Count");
        txt_avi_seat.setBorder(null);
        txt_avi_seat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_avi_seatMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_avi_seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 390, 40));
        basepanel_settings.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 390, 20));

        txt_From.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_From.setForeground(new java.awt.Color(153, 153, 153));
        txt_From.setText("From");
        txt_From.setBorder(null);
        txt_From.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_FromMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_From, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 390, 40));
        basepanel_settings.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 390, 20));

        txt_To.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_To.setForeground(new java.awt.Color(153, 153, 153));
        txt_To.setText("To");
        txt_To.setBorder(null);
        txt_To.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ToMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_To, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 390, 40));
        basepanel_settings.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 390, 20));

        txt_Date.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(153, 153, 153));
        txt_Date.setText("Date");
        txt_Date.setBorder(null);
        txt_Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_DateMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 390, 40));
        basepanel_settings.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 390, 20));

        btn_Delete.setBackground(new java.awt.Color(41, 53, 65));
        btn_Delete.setOpaque(false);
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DeleteMousePressed(evt);
            }
        });
        btn_Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Delete");
        btn_Delete.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, -1, 30));

        basepanel_settings.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 390, 60));

        btn_Update.setBackground(new java.awt.Color(41, 53, 65));
        btn_Update.setOpaque(false);
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_UpdateMousePressed(evt);
            }
        });
        btn_Update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update");
        btn_Update.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, -1, 30));

        basepanel_settings.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 390, 60));

        btn_Create.setBackground(new java.awt.Color(41, 53, 65));
        btn_Create.setOpaque(false);
        btn_Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CreateMousePressed(evt);
            }
        });
        btn_Create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Create");
        btn_Create.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, -1, 30));

        basepanel_settings.add(btn_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 390, 60));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 38)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Create New Route");
        basepanel_settings.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 300, 50));

        jSeparator7.setForeground(new java.awt.Color(0, 255, 255));
        jSeparator7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 5, true));
        basepanel_settings.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, 5));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 38)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Delete Route");
        basepanel_settings.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 300, 50));

        jSeparator8.setForeground(new java.awt.Color(0, 255, 255));
        jSeparator8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 5, true));
        basepanel_settings.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 100, 5));
        basepanel_settings.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 390, 20));

        txt_bus_no.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_bus_no.setForeground(new java.awt.Color(153, 153, 153));
        txt_bus_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_bus_no.setText("Bus Number ( if updating )");
        txt_bus_no.setBorder(null);
        txt_bus_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_bus_noMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_bus_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 390, 40));

        txt_delete_bus_no.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_delete_bus_no.setForeground(new java.awt.Color(153, 153, 153));
        txt_delete_bus_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_delete_bus_no.setText("Bus Number");
        txt_delete_bus_no.setBorder(null);
        txt_delete_bus_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_delete_bus_noMouseClicked(evt);
            }
        });
        basepanel_settings.add(txt_delete_bus_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 390, 40));
        basepanel_settings.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 390, 20));

        jPanel1.add(basepanel_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 1310, 740));

        basepanel_reser.setBackground(new java.awt.Color(255, 255, 255));
        basepanel_reser.setForeground(new java.awt.Color(255, 255, 255));
        basepanel_reser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rese_Scroll_pane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Rese_Scroll_pane.setToolTipText("");
        Rese_Scroll_pane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Rese_table.setAutoCreateRowSorter(true);
        Rese_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Rese_table.setGridColor(new java.awt.Color(255, 255, 255));
        Rese_table.setIntercellSpacing(new java.awt.Dimension(5, 5));
        Rese_table.setRowHeight(25);
        Rese_table.setSelectionBackground(new java.awt.Color(41, 39, 40));
        Rese_Scroll_pane.setViewportView(Rese_table);

        basepanel_reser.add(Rese_Scroll_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1220, 530));

        btn_reser_cancel.setBackground(new java.awt.Color(41, 53, 65));
        btn_reser_cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_reser_cancel.setOpaque(false);
        btn_reser_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_reser_cancelMousePressed(evt);
            }
        });
        btn_reser_cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Book1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        txt_Book1.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book1.setText("Cancel Reservation");
        txt_Book1.setToolTipText("");
        btn_reser_cancel.add(txt_Book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 15, -1, 20));

        basepanel_reser.add(btn_reser_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 280, 50));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 38)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Reservations");
        jLabel14.setToolTipText("");
        basepanel_reser.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, 50));

        jSeparator21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        basepanel_reser.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 5));

        jPanel1.add(basepanel_reser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 1310, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMousePressed
        // TODO add your handling code here:

        Connection con = null;
        javax.swing.JTable Table = jTable_report;
        SQlConnection a = new SQlConnection();
        GetTableData Data = new GetTableData();

        if ((txt_date.getText().equals("YYYY/MM/DD") && txt_from.getText().equals("From") && txt_to.getText().equals("To")) || (txt_date.getText().equals("") && txt_from.getText().equals("") && txt_to.getText().equals(""))) {

            JOptionPane.showMessageDialog(null, "Please Insert data to search");
            try {

                con = a.connect();
                String sql = "Select * from timetable";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                Data.gatitem(rs, Table);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {

            if (txt_from.getText().equals("") || txt_to.getText().equals("")) {

                try {

                    con = a.connect();
                    String sql = "Select * from timetable where Date=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, txt_date.getText());
                    ResultSet rs = pst.executeQuery();
                    Data.gatitem(rs, Table);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else {
                if (txt_date.getText().equals("")) {
                    try {

                        con = a.connect();
                        String sql = "Select * from timetable where Bus_from='" + txt_from.getText() + "' AND Bus_to='" + txt_to.getText() + "'";
                        PreparedStatement pst = con.prepareStatement(sql);
                        ResultSet rs = pst.executeQuery();
                        Data.gatitem(rs, Table);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                } else {

                    try {

                        con = a.connect();
                        String sql = "Select * from timetable where Bus_from='" + txt_from.getText() + "' AND Bus_to='" + txt_to.getText() + "' AND Date='" + txt_date.getText() + "'";
                        PreparedStatement pst = con.prepareStatement(sql);
                        ResultSet rs = pst.executeQuery();
                        Data.gatitem(rs, Table);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                }

            }
        }


    }//GEN-LAST:event_btn_SearchMousePressed

    private void btn_AccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AccMousePressed
        // TODO add your handling code here:
        a.setColor(btn_Acc);
        a.resetColor(btn_home);
        a.resetColor(btn_reser);
        a.resetColor(btn_settings);

        a.setpanelColor(panel_Acc);
        a.resetColor(panel_Repo);
        a.resetColor(panel_home);
        a.resetColor(panel_settings);

        basepanel_settings.setVisible(false);
        basepanel_Account.setVisible(true);
        basepanel_reser.setVisible(false);
        basepanel_home.setVisible(false);

    }//GEN-LAST:event_btn_AccMousePressed

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        a.setColor(btn_home);
        a.resetColor(btn_reser);
        a.resetColor(btn_Acc);
        a.resetColor(btn_settings);

        a.setpanelColor(panel_home);
        a.resetColor(panel_Repo);
        a.resetColor(panel_Acc);
        a.resetColor(panel_settings);

        basepanel_settings.setVisible(false);
        basepanel_Account.setVisible(false);
        basepanel_reser.setVisible(false);
        basepanel_home.setVisible(true);

        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {
            con = a.connect();
            String sql = "Select * from timetable";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            jTable_report.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_reserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reserMousePressed
        // TODO add your handling code here:
        a.setColor(btn_reser);
        a.resetColor(btn_home);
        a.resetColor(btn_Acc);
        a.resetColor(btn_settings);

        a.setpanelColor(panel_Repo);
        a.resetColor(panel_home);
        a.resetColor(panel_Acc);
        a.resetColor(panel_settings);

        basepanel_settings.setVisible(false);
        basepanel_Account.setVisible(false);
        basepanel_reser.setVisible(true);
        basepanel_home.setVisible(false);

        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {
            con = a.connect();
            String sql = "Select * from bookings WHERE Customer_Num=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, current);
            ResultSet rs = pst.executeQuery();
            Rese_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_reserMousePressed

    private void btn_settingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingsMousePressed
        // TODO add your handling code here:
        a.setColor(btn_settings);
        a.resetColor(btn_home);
        a.resetColor(btn_Acc);
        a.resetColor(btn_reser);

        a.setpanelColor(panel_settings);
        a.resetColor(panel_home);
        a.resetColor(panel_Acc);
        a.resetColor(panel_Repo);

        basepanel_settings.setVisible(true);
        basepanel_Account.setVisible(false);
        basepanel_reser.setVisible(false);
        basepanel_home.setVisible(false);
//        Settings settings = new Settings();
//        settings.setVisible(true);
//        setVisible(false);
    }//GEN-LAST:event_btn_settingsMousePressed

    private void close_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_buttonMousePressed

    private void btn_BookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BookMousePressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable_report.getModel();
        int row = jTable_report.getSelectedRow();
        // int column =jTable_report.getSelectedColumn();
        ;
        if (row >= 0) {
            //model.removeRow(row);
            String col1 = model.getValueAt(row, 0).toString();
            String col7 = model.getValueAt(row, 6).toString();
            String col8 = model.getValueAt(row, 7).toString();

            String col9 = model.getValueAt(row, 8).toString();

            Connection con = null;
            SQlConnection a = new SQlConnection();
            try {
                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                Date date = fmt.parse(col9);
                java.util.Date utilDate = date;
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                final String stringDate = dateFormat.format(utilDate);
                final java.sql.Date sqlDate = java.sql.Date.valueOf(stringDate);

                con = a.connect();
                String sql = "INSERT INTO `bookings`(`Customer_Num`, `Bus_Num`,`Date`, `Bus_from`, `Bus_to`) VALUES (?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, current);
                pst.setString(2, col1);
                pst.setDate(3, sqlDate);
                pst.setString(4, col7);
                pst.setString(5, col8);

                pst.executeUpdate();
                pst.close();
                con.close();
                JOptionPane.showMessageDialog(null, "Sucessfully Record inserted");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Connect the Database");
        }


    }//GEN-LAST:event_btn_BookMousePressed

    private void txt_dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dateMouseClicked

        txt_date.setText("");
    }//GEN-LAST:event_txt_dateMouseClicked

    private void txt_fromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fromMouseClicked

        txt_from.setText("");
    }//GEN-LAST:event_txt_fromMouseClicked

    private void txt_toMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_toMouseClicked

        txt_to.setText("");
    }//GEN-LAST:event_txt_toMouseClicked

    private void txt_arrivalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_arrivalMouseClicked

        txt_arrival.setText("");
    }//GEN-LAST:event_txt_arrivalMouseClicked

    private void txt_depatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_depatureMouseClicked
        // TODO add your handling code here:
        txt_depature.setText("");
    }//GEN-LAST:event_txt_depatureMouseClicked

    private void txt_conditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_conditionMouseClicked
        // TODO add your handling code here:
        txt_condition.setText("");
    }//GEN-LAST:event_txt_conditionMouseClicked

    private void txt_seatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_seatMouseClicked
        // TODO add your handling code here:
        txt_seat.setText("");
    }//GEN-LAST:event_txt_seatMouseClicked

    private void txt_avi_seatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_avi_seatMouseClicked
        // TODO add your handling code here:
        txt_avi_seat.setText("");
    }//GEN-LAST:event_txt_avi_seatMouseClicked

    private void txt_FromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FromMouseClicked
        // TODO add your handling code here:
        txt_From.setText("");
    }//GEN-LAST:event_txt_FromMouseClicked

    private void txt_ToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ToMouseClicked
        // TODO add your handling code here:
        txt_To.setText("");
    }//GEN-LAST:event_txt_ToMouseClicked

    private void txt_DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_DateMouseClicked
        // TODO add your handling code here:
        txt_Date.setText("");
    }//GEN-LAST:event_txt_DateMouseClicked

    private void btn_CreateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CreateMousePressed

        String arri = txt_arrival.getText();
        String depa = txt_depature.getText();
        String from = txt_From.getText();
        String to = txt_To.getText();
        String seats = txt_seat.getText();
        String avilseats = txt_avi_seat.getText();
        String condition = txt_condition.getText();
        String Date = txt_Date.getText();

        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            Date date = fmt.parse(Date);
            java.util.Date utilDate = date;
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            final String stringDate = dateFormat.format(utilDate);
            final java.sql.Date sqlDate = java.sql.Date.valueOf(stringDate);

            con = a.connect();
            String sql = "INSERT INTO `timetable`(`Arrival`,`Departure`, `Bus_condition`, `Seats`,`Avi_seates`,`Bus_from`,`Bus_to`,`Date` ) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, arri);
            pst.setString(2, depa);
            pst.setString(3, condition);
            pst.setString(4, seats);
            pst.setString(5, avilseats);
            pst.setString(6, from);
            pst.setString(7, to);
            pst.setDate(8, sqlDate);

            pst.executeUpdate();
            pst.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Sucessfull Record Inserted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_CreateMousePressed

    private void btn_UpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMousePressed

        String arri = txt_arrival.getText();
        String depa = txt_depature.getText();
        String from = txt_From.getText();
        String to = txt_To.getText();
        String seats = txt_seat.getText();
        String avilseats = txt_avi_seat.getText();
        String condition = txt_condition.getText();
        String Date = txt_Date.getText();
        String busno = txt_bus_no.getText();

        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            Date date = fmt.parse(Date);
            java.util.Date utilDate = date;
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            final String stringDate = dateFormat.format(utilDate);
            final java.sql.Date sqlDate = java.sql.Date.valueOf(stringDate);

            con = a.connect();
            String sql = "UPDATE `timetable` SET `Arrival`=?,`Departure`=?, `Bus_condition`=?, `Seats`=?,`Avi_seates`=?,`Bus_from`=?,`Bus_to`=?,`Date`=? WHERE `Bus_num`=?";

            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, arri);
            pst.setString(2, depa);
            pst.setString(3, condition);
            pst.setString(4, seats);
            pst.setString(5, avilseats);
            pst.setString(6, from);
            pst.setString(7, to);
            pst.setDate(8, sqlDate);
            pst.setString(9, busno);

            pst.executeUpdate();
            pst.close();
            con.close();

            JOptionPane.showMessageDialog(null, "Successfuly Updated the route");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_UpdateMousePressed

    private void txt_bus_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_bus_noMouseClicked
        // TODO add your handling code here:
        txt_bus_no.setText("");
    }//GEN-LAST:event_txt_bus_noMouseClicked

    private void txt_delete_bus_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_delete_bus_noMouseClicked
        // TODO add your handling code here:
        txt_delete_bus_no.setText("");
    }//GEN-LAST:event_txt_delete_bus_noMouseClicked

    private void btn_DeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMousePressed

        String busno = txt_delete_bus_no.getText();
        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {

            con = a.connect();
            String sql = "DELETE FROM `timetable` WHERE `Bus_num`=?";

            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, busno);

            pst.executeUpdate();
            pst.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Successfuly deleted the route");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btn_DeleteMousePressed

    private void txt_surnanmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_surnanmeMouseClicked
        // TODO add your handling code here:
        txt_surnanme.setText("");
    }//GEN-LAST:event_txt_surnanmeMouseClicked

    private void txt_passwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwdMouseClicked
        // TODO add your handling code here:
        txt_passwd.setText("");
    }//GEN-LAST:event_txt_passwdMouseClicked

    private void txt_dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dobMouseClicked
        // TODO add your handling code here:
        txt_dob.setText("");
    }//GEN-LAST:event_txt_dobMouseClicked

    private void txt_mobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mobileMouseClicked
        // TODO add your handling code here:
        txt_mobile.setText("");
    }//GEN-LAST:event_txt_mobileMouseClicked

    private void txt_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMouseClicked
        // TODO add your handling code here:
        txt_email.setText("");
    }//GEN-LAST:event_txt_emailMouseClicked

    private void txt_firstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstnameMouseClicked
        // TODO add your handling code here:
        txt_firstname.setText("");
    }//GEN-LAST:event_txt_firstnameMouseClicked

    private void txt_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addressMouseClicked
        // TODO add your handling code here:
        txt_address.setText("");
    }//GEN-LAST:event_txt_addressMouseClicked

    private void btn_imageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imageMousePressed
        // TODO add your handling code here:

        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
            fileChooser.addChoosableFileFilter(filter);
            int result = fileChooser.showSaveDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                lbl_image.setIcon(ResizeImage(path));
                s = path;
            } else if (result == JFileChooser.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(null, "No Data");
            }
            Connection con = null;
            SQlConnection a = new SQlConnection();
            try {
                con = a.connect();
                String sql = "UPDATE `login` SET `image`=? WHERE `sno`=?";
                PreparedStatement pst = con.prepareStatement(sql);
                InputStream is = new FileInputStream(new File(s));

                pst.setBlob(1, is);
                pst.setInt(2, current);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data inserted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_imageMousePressed

    private void btn_acc_updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acc_updateMousePressed

        boolean que1 = txt_surnanme.getText().trim().isEmpty() || txt_firstname.getText().trim().isEmpty() || txt_passwd.getText().trim().isEmpty() || txt_email.getText().trim().isEmpty() || txt_dob.getText().trim().isEmpty() || txt_mobile.getText().trim().isEmpty() || txt_address.getText().trim().isEmpty();

        if (que1) {
            JOptionPane.showMessageDialog(null, "Please Enter Data");
        } else {

            Connection con = null;
            SQlConnection a = new SQlConnection();
            try {
                String sname = txt_surnanme.getText();
                String fname = txt_firstname.getText();
                String pass = txt_passwd.getText();
                String email = txt_email.getText();
                String dob = txt_dob.getText();
                String mobile = txt_mobile.getText();
                String address = txt_address.getText();

                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                Date date = fmt.parse(dob);
                java.util.Date utilDate = date;
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                final String stringDate = dateFormat.format(utilDate);
                final java.sql.Date sqlDate = java.sql.Date.valueOf(stringDate);

                con = a.connect();
                String sql = "UPDATE `login` SET `firstname`=?,`password`=?,`Email`=?,`phone`=?,`address`=?,`surname`=?,`dob`=? WHERE `sno`=?";
                PreparedStatement pst = con.prepareStatement(sql);

                pst.setString(1, fname);
                pst.setString(2, pass);
                pst.setString(3, email);
                pst.setString(4, mobile);
                pst.setString(5, address);
                pst.setString(6, sname);
                pst.setDate(7, sqlDate);
                pst.setInt(8, current);

                pst.executeUpdate();
                con.close();

                JOptionPane.showMessageDialog(null, "Data inserted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }

    }//GEN-LAST:event_btn_acc_updateMousePressed

    private void btn_reser_cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reser_cancelMousePressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Rese_table.getModel();
        int row = Rese_table.getSelectedRow();
        String invonum = model.getValueAt(row, 0).toString();

        Connection con = null;
        SQlConnection a = new SQlConnection();
        try {
            con = a.connect();
            String sql = "DELETE FROM `bookings` WHERE `Invoice_Num`=?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, invonum);
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "Selected row deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_reser_cancelMousePressed

    private void btn_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMousePressed
        // TODO add your handling code here:
        Login login=new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_logoutMousePressed

    //##### Importing Color Changes to Side Panel Buttons
    ChangeButtonColor a = new ChangeButtonColor();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Rese_Scroll_pane;
    private javax.swing.JTable Rese_table;
    private javax.swing.JPanel basepanel_Account;
    private javax.swing.JPanel basepanel_home;
    private javax.swing.JPanel basepanel_reser;
    private javax.swing.JPanel basepanel_settings;
    private javax.swing.JPanel btn_Acc;
    private javax.swing.JPanel btn_Book;
    private javax.swing.JPanel btn_Create;
    private javax.swing.JPanel btn_Delete;
    private javax.swing.JPanel btn_Search;
    private javax.swing.JPanel btn_Update;
    private javax.swing.JPanel btn_acc_update;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_image;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_reser;
    private javax.swing.JPanel btn_reser_cancel;
    private javax.swing.JPanel btn_settings;
    private javax.swing.JLabel close_button;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable_report;
    private javax.swing.JLabel lbl_Realtime_username;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_username2;
    private javax.swing.JLabel lbl_username3;
    private javax.swing.JLabel lbl_username4;
    private javax.swing.JPanel left_main_panel;
    private javax.swing.JPanel panel_Acc;
    private javax.swing.JPanel panel_Repo;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JPanel panel_settings;
    private javax.swing.JPanel panel_top;
    private javax.swing.JLabel txt_Book;
    private javax.swing.JLabel txt_Book1;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_From;
    private javax.swing.JTextField txt_To;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_arrival;
    private javax.swing.JTextField txt_avi_seat;
    private javax.swing.JTextField txt_bus_no;
    private javax.swing.JTextField txt_condition;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_delete_bus_no;
    private javax.swing.JTextField txt_depature;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_from;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_passwd;
    private javax.swing.JLabel txt_search;
    private javax.swing.JTextField txt_seat;
    private javax.swing.JTextField txt_surnanme;
    private javax.swing.JTextField txt_to;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
            //graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border

        }
    }
    //Get Current User
    int snumber;
    current_user x = new current_user();
    int current = x.current(snumber);

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

}
